### PR TITLE
fix: add api for datastore/admin

### PR DESCRIPTION
**Pull request by dmitry-fa**
see PR https://github.com/googleapis/java-datastore/pull/119 for demonstration of generated files

### CODE REVIEW

**Comment by BenWhitehead** [comment]
We can't merge this until other work toward v2 has landed. I've tagged it as blocked and targeting milestone v2.

**Comment by xSAVIKx** [comment]
> We can't merge this until other work toward v2 has landed. I've tagged it as blocked and targeting milestone v2.
> 
> No code change needed from @dmitry-fa at this time.

Is there any timeline when this PR could be merged? We do rely on the Admin API and right now are forced to generate and use Admin Protos directly. It'd be really great to have them as part of the library.

**Comment by meredithslota** [comment]
@BenWhitehead v2 has been out for some time — is this PR still relevant?

**Comment by kolea2** [comment]
Done in: https://github.com/googleapis/java-datastore/pull/748

**Pull request closed without merging**
